import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const header = (
    <header>
      <div>
        <Link href='/'>
          <h1>Oliver's Blog</h1>
        </Link>  
        <p>🤟 Welcome to my tech blog. 💻</p>
        <br />
      </div>
    </header>
  )

  const footer = (
    <footer>
      <div>
        <br />
        <h3>Developed by Oliver</h3>
      </div>
    </footer>
  )

  return (
    <html lang="en">
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  )
}
